name: Test

on: [push]

jobs:
    test-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4.2.2

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.4.0
              with:
                node-version: latest

            - name: node version
              run: node --version
            
            - name: Install
              run: npm install 